### ISSUE TITLE
how support uuid in greenplum???

### ISSUE THREAD

**Issue by zhangle1024** [greenplum-db/greenplum-db.github.io#23]
hello,everyone!
    how can support uuid in greenplum? uuid-1.6.x.tar.gz work on postgresql, but not work in greenplum DB. help! please!!!

**Comment by danielgustafsson** [comment]
UUID is not a supported datatype in any released version of Greenplum, it will however be in the upcoming 5.0 release.

Please direct usage questions to the gpdb-users mailinglist, see http://greenplum.org/#mailing-lists for more information.
