### ISSUE TITLE
Spreadsheet Updates?

### ISSUE THREAD

**Issue by inviscid** [greenplum-db/greenplum-db.github.io#25]
Hi - very interested in this as we use Greenplum but would very much like to use all the new goodness in PG 9+.  I noticed there are no updates on progress in the spreadsheet link.  Is there a different spreadsheet we should look at?

Thanks for getting this started.  Excited to see Greenplum incorporate the latest features.

**Comment by danielgustafsson** [comment]
I assume you mean the spreadsheet in the Wiki for tracking the merge with PostgreSQL. That spreadsheet didn't really get a lot of attention when we switched merge strategy, but it's not clear when looking at it. For the upcoming Greenplum 5.0 release we have merged all of PostreSQL 8.3 as well as some cherry-picked features from later versions. While 8.3 is still a way from "latest", it's an important milestone towards catching up. The pace of merging will be faster for future Greenplum releases, it won't be limited to one PostgreSQL release per Greenplum release.

**Comment by inviscid** [comment]
Excellent.  It is great to hear that catching up is a priority.  There have been both syntactic improvements as well as code refinements learned through a lot of hard work and introspection in the Postgres community.  We will continue to watch the releases closely.

Thanks again for all the work on this incredible tool.
