### ISSUE TITLE
Tutorial content overflows without scroll on 13" window

### ISSUE THREAD

**Issue by danielgustafsson** [greenplum-db/greenplum-db.github.io#34]
The menu on the new tutorial section overflows on a small window (full screen on a 13" laptop) with no scroll available, rendering the content unreachable. That being said, the previous version had the same problem, but the menu wasn't as tall and thus didn't really pose the same problem.

See attached screenshot from my machine:

<img width="1274" alt="screen shot 2017-08-11 at 16 43 44" src="https://user-images.githubusercontent.com/321790/29218251-7e8e0018-7eb4-11e7-8573-1a273a1a14f2.png">

**Comment by jacksoncvm** [comment]
The structure is a little odd... as a quickfix, you can move the sidebar up and maybe take out some of the spacing between the items.

**Comment by danielgustafsson** [comment]
Fixed in PR 19 in the tutorial repo.
