### ISSUE TITLE
After building GP DB, its showing up directory not found

### ISSUE THREAD

**Issue by nellaivijay** [greenplum-db/greenplum-db.github.io#5]
After building GP DB, its showing up directory not found
```
[gpadmin@localhost ~]$ python ~/gpdb/bin/gpstop
20160206:13:07:44:026834 gpstop:localhost:gpadmin-[INFO]:-Starting gpstop with args: 
20160206:13:07:44:026834 gpstop:localhost:gpadmin-[INFO]:-Gathering information and validating the environment...
20160206:13:07:44:026834 gpstop:localhost:gpadmin-[CRITICAL]:-gpstop failed. (Reason='[Errno 2] No such file or directory: '/home/gpadmin/data/master/gpseg-/postgresql.conf'') exiting...
```

**Comment by danielgustafsson** [comment]
Hi,

This repository is only for the Greeplum website and not the database per se. Did you follow the instructions in the README.md file for how to create a demo cluster? It's better to raise these questions on the GPDB Users mailing list, please see http://greenplum.org for instructions on how to subscribe.
